<link rel="stylesheet" type="text/css" href="style/style.css">
<link rel="stylesheet" type="text/css" href="style/menu.css">
<link rel="stylesheet" type="text/css" href="style/main.css">
<link rel="stylesheet" type="text/css" href="style/headpoisk.css">
<link rel="stylesheet" type="text/css" href="style/katalog.css">
<link rel="stylesheet" type="text/css" href="style/loginregistration.css">
<link rel="stylesheet" type="text/css" href="style/type_product.css">
<link rel="stylesheet" type="text/css" href="style/modal.css">
<link rel="stylesheet" type="text/css" href="style/slyder.css">
<link rel="stylesheet" type="text/css" href="style/footer.css">
<link rel="stylesheet" type="text/css" href="style/loginBtn.css">